services:
  iso_erp:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: iso_erp
    working_dir: /app
    command: ["dotnet", "ISO_ERP.dll"]
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
    volumes:
      - /volume1/docker/iso_erp:/app_old
      - /volume1/ISO3834-3/03_R:/excel
    restart: unless-stopped